title: EE485 Programming Structures for Electrical Engineering

url: https://computer.kaist.ac.kr
baseurl: /

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-redirect-from

minima_reboot:
  date_format: "%b %-d, %Y"
  date_format_short: "%b %-d"

header_pages:
# - precepts.md
- assign.md
- policy.md

paginate: 5

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - minima-reboot.gemspec
  - vendor/bundle
